# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2b1c263c6c338b1e54ed2232983a5dad36a8b6a261e6f0aa80de10aeb250a8efebe48831d42994e953ef47f2cb26cc611f3f94c001e878611cc12c809e485b5

test:
  secret_key_base: b14bc30478ea2c4bfafba7618fa9a1ba212295494368aecf97eda42a5b31961c169cc03a4efeb40a048719266d375d1262d3673233f99e6e95145a4b0ba75f9c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
